### ISSUE TITLE
Before reaching 0.9.0, go through a checklist for Open Source projects

### ISSUE THREAD

**Issue by fgeorgatos** [qtop/qtop#154]
Basically, here is the checklist:
* http://afonsopacifer.github.io/open-source-checklist/ 

Possibly, adopt a very brief text for CONTRIBUTING.md like the following:
```
Please follow the conventions common of Open Source projects, such as:
https://github.com/google/material-design-lite/blob/master/CONTRIBUTING.md
```

**Comment by fgeorgatos** [comment]
Also, explain ideal PR outlook:
http://blog.ploeh.dk/2015/01/15/10-tips-for-better-pull-requests/

* 1. Make it small
* 2. Do only one thing
* 3. Watch your line width
* 4. Avoid re-formatting
* 5. Make sure the code builds
* 6. Make sure all tests pass
* 7. Add tests
* 8. Document your reasoning
* 9. Write well
* 10. Avoid thrashing # I'm against needless deletes - within reason!

**Comment by lookfwd** [comment]
I'm a bit against stating anything (discouraging) towards PRs, unless we have a problem :-)

**Comment by fgeorgatos** [comment]
it doesn't say anywhere that we won't merge non-ideal PRs :-P

On 26 February 2016 at 09:39, Dimitrios Kouzis-Loukas <
notifications@github.com> wrote:

> I'm a bit against stating anything (discouraging) towards PRs, unless we
> have a problem :-)
>
> Sent from my iPhone
>
> > On 26 Feb 2016, at 09:35, Fotis Georgatos <notifications@github.com>
> wrote:
> >
> > Also, explain ideal PR outlook:
> > http://blog.ploeh.dk/2015/01/15/10-tips-for-better-pull-requests/
> >
> > 1. Make it small
> > 2. Do only one thing
> > 3. Watch your line width
> > 4. Avoid re-formatting
> > 5. Make sure the code builds
> > 6. Make sure all tests pass
> > 7. Add tests
> > 8. Document your reasoning
> > 9. Write well
> > 10. Avoid thrashing # I'm against needless deletes - within reason!
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qtop/qtop/issues/154#issuecomment-189191770>.
>



-- 


echo "sysadmin know better bash than english"|sed s/min/mins/ \
  | sed 's/better bash/bash better/' # signal detected in a CERN forum

**Comment by fgeorgatos** [comment]
Tasks
- [x] Choose a cool name!
- [x] Create a description for your project.
- [x] Add a README.md file containing all the basic information about your project.
- [x] Create a CONTRIBUTING.md file containing all the necessary information so that other developers can help you.
- [x] Add a .gitignore file containing everything you do not want versioning .
- [x] Select and add the best license for your project.
- [x] Choose a methodology versioning and follow.
- [x] Create a roadmap to make clear the course of the project.
- [x] Document your project in the best possible way.
- [x] Describe your Releases clearly and objectively or create a CHANGELOG.md file and do it there.
- [x] Use badges to indicate the status of your project.
- [x] Configure and add a .editorconfig.
- [ ] When necessary do not hesitate to create a website for your project. Enjoy and publish with github pages.
- [x] Write automated tests
- [x] Integrate your tests a Continuous Integration service.
- [ ] Provide your project in the appropriate package manager. (EX: bower, npm, etc...)

Tricks and Tips
- [ ] Learn all about Github.
- [x] Be the master of Markdown.
- [ ] If you are a student, receive your Student Developer Pack.
- [ ] Use Emoji Emoticons.
- [ ] Always use SVG.
- [ ] Remember the existence of Gitter to integrate a chat to your repository.
- [ ] Submit your project for the appropriate newsletter.
- [ ] Submit your project for the appropriate awesome list.
- [ ] Article with more tips to create your open projects focusing on javascript :)

**Comment by fgeorgatos** [comment]
repeating, in case anybody missed it: ;-)

Possibly, adopt a very brief text for CONTRIBUTING.md like the following:

```
Please simply follow the common conventions for Open Source projects, such as:
https://github.com/google/material-design-lite/blob/mdl-1.x/CONTRIBUTING.md
```

**Comment by fgeorgatos** [comment]
Also worthy read and related: http://moo.nac.uci.edu/~hjm/How_to_Evaluate_OSS.html

**Comment by fgeorgatos** [comment]
This one really is a good first issue ; not everything needs to be fixed, just to be checked against expectations!
